name: Container Image Scan

on:
  push:
    branches: [main]     # Triggers on push to main branch, can be changed to other branches or events

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Scan container image with Anchore
        id: scan
        uses: anchore/scan-action@v7
        with:
          image: casthighlight/cli:5.11.15
          fail-build: true
          severity-cutoff: high
          output-format: json
          output-file: anchore-scan-results.json

      - name: Upload Anchore scan JSON report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: anchore-scan-report
          path: anchore-scan-results.json
          retention-days: 30
